### PR TITLE
Put cqlsh into a separate package

### PR DESCRIPTION
**Pull request by dmitry-potepalov**
Necessary to reuse this separate package in cassandra3

### CODE REVIEW

**Review by facetoe — DISMISSED** [review]
LGTM, need deps links to show it builds no worries on f33 and f34

**Comment by dmitry-potepalov** [comment]
Here's the [f33 deps build](https://j27.dev.aiven.fi:4343/job/user-aiven-deps-f33/1972/artifact/) with the relevant packages.
Here's the [f34 deps build](https://j27.dev.aiven.fi:4343/job/user-aiven-deps-f34/86/) as proof that Cassandra and it's Python driver now build under f34 after cqlsh separation.

**Review by facetoe — CHANGES_REQUESTED** [review]
I was about to merge this then it occurred to me, do we need to require this now somewhere so it gets installed with normal Cassandra? Otherwise I guess if we build Cassandra it wouldn't work as cqlsh would be missing. Also as we changed the recipe should bump the release so we can run the tests etc against the new packages.

**Comment by dmitry-potepalov** [comment]
It's required in the matching [PR](https://github.com/aiven/aiven-core/pull/15796) in `aiven-core`, I've changed the `aiven-deps` spec to require `clqsh4` for `cassandra3`

**Review by facetoe — DISMISSED** [review]
I guess that requires should be in this PR and the release bumped as otherwise this PR doesn't stand alone and the resulting package if we were to build it would be broken due to missing clqsh.

**Comment by dmitry-potepalov** [comment]
what do you mean by "broken"? the core/package compatibility is preserved by using appropriate commits in core. Modifications to the `aiven-3.11.5` branch are not immediately propagated, therefore even if this gets merged - core is not broken.

Or is there another package build scenario I'm not aware of?
If you mean "broken" in the general sense - `cqlsh` is not necessary to run the server, removing it does not affect the ability to start `cassandra`

**Comment by facetoe** [comment]
Ahh, it seems I am making a bit of a habit of this. I missed this was on the Cassandra repo and thought it was in Aiven core...

**Pull request merged**
