### PR TITLE
Apply Aiven-specific changes on top of upstream 4.1.3

### PR DESCRIPTION
**Pull request by meatlink**
- changes related to .spec file were omitted, we do not need them anymore
- RF uptuning functionality were omitted, because now we have guardrails framework for that

### CODE REVIEW

**Comment by sjamgade** [comment]
the 4.0.11 branch seems to have this commit https://github.com/aiven/cassandra/commit/7372136e512afdd7293b409afbcdaca3c3278821 do we not need it here ?

**Comment by alanfranz** [comment]
> the 4.0.11 branch seems to have this commit [7372136](https://github.com/aiven/cassandra/commit/7372136e512afdd7293b409afbcdaca3c3278821) do we not need it here ?

Yes, we need that or we'll get back to a vulnerable version. I'm surprised this wasn't fixed upstream. @meatlink 

EDIT:
it's on the 4.1 branch upstream but they didn't do any release since July.

**Review by sjamgade — DISMISSED** [review]
requesting changes based on comment above

**Comment by alanfranz** [comment]
I'm trying the "assignee" workflow and arbitrarily assigned @sjamgade to this :-)

**Review by sjamgade — APPROVED** [review]
yay, CI passed

**Pull request merged**
