### PR TITLE
Apply Aiven-specific changes on top of upstream 4.1.5

### PR DESCRIPTION
**Pull request by tilman-aiven**
Changes

- https://github.com/apache/cassandra/blob/cassandra-4.1.5/CHANGES.txt
- https://github.com/apache/cassandra/blob/cassandra-4.1.4/CHANGES.txt

Dropped commit

- https://github.com/aiven/cassandra/pull/21/commits/158a1778559fb07819b4eb586d4436d2d51ab20c  (obsolete)

# Test runs

## (1)

Warning in org.apache.cassandra.cql3.MemtableSizeTest
- Expected heap usage close to 75.529MiB, got 71.597MiB.
- https://issues.apache.org/jira/browse/CASSANDRA-16684
- https://issues.apache.org/jira/browse/CASSANDRA-17298
- https://www.mail-archive.com/commits@cassandra.apache.org/msg297135.html
- https://github.com/apache/cassandra/commit/3875fd26ea3c16e57bf08454d570e3359d2ce5fc
- https://butler.cassandra.apache.org/#/ci/upstream/compare/Cassandra-4.0/cassandra-4.0

### CODE REVIEW

**Comment by tilman-aiven** [comment]
testSize[skiplist] (org.apache.cassandra.cql3.MemtableSizeTest) failed (warning)
```
junit.framework.AssertionFailedError: Expected heap usage close to 75.526MiB, got 71.473MiB.

	at org.apache.cassandra.cql3.MemtableSizeTest.testSizeFlaky(MemtableSizeTest.java:149)
	at org.apache.cassandra.Util.runCatchingAssertionError(Util.java:696)
	at org.apache.cassandra.Util.flakyTest(Util.java:721)
	at org.apache.cassandra.cql3.MemtableSizeTest.testSize(MemtableSizeTest.java:81)
```
Based on [CASSANDRA-17298](https://issues.apache.org/jira/browse/CASSANDRA-17298) they changed the memtable_allocation_type to heap_buffers (in the unit test).
As  a result the test now fails in 4.0 and 4.1. Only the test is broken.

**Comment by tilman-aiven** [comment]
https://aiven-io.slack.com/archives/C052RDBD1TP/p1718867347237329?thread_ts=1718866820.372779&cid=C052RDBD1TP

- increase the threshold testSize[skiplist] (org.apache.cassandra.cql3.MemtableSizeTest)

**Comment by tilman-aiven** [comment]
@sjamgade 
During the daily the suggestion was to keep the flaky test untouched, as long as we get the build.

The reason why the test fails

- By default we use heap_buffers in cassandra.yaml, but the unit tests were switched for testing to offheap_objects. This needs to be reverted. We should be testing with heap_buffers on all branches, we do it only in cassandra-3.0 at the moment. 
- It was discovered that unit tests were running with memtable_allocation_type: offheap_objects when we ship C* with heap_buffers.
- So we changed that in CASSANDRA-19326, now we test with memtable_allocation_type: heap_buffers. As a result, this test now fails all the time on 4.0 and 4.1.

The severity is low ([CASSANDRA-17298](https://issues.apache.org/jira/browse/CASSANDRA-17298))
I could successfully build with `ant build`

**Review by sjamgade — APPROVED** [review]
LGTM

**Pull request merged**
